### ISSUE TITLE
Opencomputer book cause stop responsing 

### ISSUE THREAD

**Issue by coronanimo** [TartaricAcid/Minecraft-Mod-Language-Package#100]
Repro:

Use Forge & Opencomputer only
Load Resource Pack of Language
Change language to Simplified Chinese
Create game , open the book in initial inventory
All stops!

**Comment by 3TUSK** [comment]
MightyPirates/OpenComputers#2395

**Comment by mgdgfbhevdyeh** [comment]
it's fixed is OpenComputers repository
try update your OpenComputers version.
