### ISSUE TITLE
mystical agriculture 翻译错误和更新

### ISSUE THREAD

**Issue by exia00125** [TartaricAcid/Minecraft-Mod-Language-Package#117]
//精华锭块翻成精华块
tile.ma.base_essence_ingot_block.name=基础精华锭块
tile.ma.inferium_ingot_block.name=§e下级精华锭块
tile.ma.prudentium_ingot_block.name=§a初级精华锭块
tile.ma.intermedium_ingot_block.name=§6中级精华锭块
tile.ma.superium_ingot_block.name=§b高级精华锭块
tile.ma.supremium_ingot_block.name=§c终极精华锭块

//作者更新AA焦黑石英
tile.ma.black_quartz_crop.name=焦黑石英作物

item.ma.black_quartz_essence.name=焦黑石英精华

item.ma.black_quartz_seeds.name=焦黑石英种子

//放置光源翻成防止光源
desc.ma.charm_miners_vision=允许你放置无限的光源。

**Comment by 3TUSK** [comment]
你可以选择 Pull Request...

**Comment by mgdgfbhevdyeh** [comment]
您可以提交PR

**Comment by exia00125** [comment]
新手第一次用，已经提交了
