### ISSUE TITLE
BTM Moon?

### ISSUE THREAD

**Issue by 3TUSK** [TartaricAcid/Minecraft-Mod-Language-Package#121]
[Yes, it is a thing now.](http://btm.asie.pl/moon/)

Last year, I conducted a operation (3TUSK/Temp-l10n#65) aiming to provide as much i18n/l10n support for those Chinese players. How about this year? Also for sake of pushing forward to 1.12.1.

还记得去年的 3TUSK/Temp-l10n#65 吗？我觉得今年可能需要再来一遍... 算是推动一下 1.12.1 吧。

**Comment by TartaricAcid** [comment]
几月份开始？

**Comment by 3TUSK** [comment]
11月。点开那个链接你能看到 "November" 的。

**Comment by asiekierka** [comment]
We are probably going to be freezing the modpack a few days before November 17th, so I'd say "early November" would be a good point to aim at.

**Comment by 3TUSK** [comment]
I'd say better start earlier than sorry - I checked yesterday, Nov. 17th is pretty close to Thanksgiving week in U.S. (intended?), but it's not a thing in China though.

> Especially when we encounter hardcoded string.

**Comment by 3TUSK** [comment]
Ok here it is: the mirrored mod list from http://btm.asie.pl/moon/, used for tracking translation progress.
This list will be update regularly (before the list is settle down), please check regularly.

下表为 http://btm.asie.pl/moon/ 上的 mod 列表的镜像，用于跟踪翻译进度。在最终 mod 列表确定前都会定期更新，请定期查阅。


|Mod|Author/作者|Assignee/指定翻译者|
|:------|:------|:------|
|Additional Banners|Darkhax|
|Aqua Munda|McJty|
|Architect|Sangar|
|Aroma1997's Dimensional World Mod|Aroma1997|
|Aroma1997's GPS Mod|Aroma1997|
|Autoverse|masa|
|Bedrock Ores|Sangar|
|Better With Mods|Better With Mods Team|
|Binnie's Mods|Binnie567, Forestry Team|
|Catwalks 3|TheCodeWarrior|
|Charset|asie|
|Chisel|Chisel developers|
|Computronics|Vexatos|
|Cyclic|Lothrazar|
|Dark Utilities|Darkhax|
|Deep Resonance|McJty|
|Elemental Dimensions|McJty|
|Ender Utilities|masa|
|Engination|Falkreon|
|EvilCraft|kroeser|
|Exchanges|Jacky1356400|
|Flamingo|Vexatos|
|Forestry|mezz, Forestry Team|
|Gear Swapper|McJty|
|ImmersiveCraft|McJty|
|IndustrialCraft 2|IC2 Team|
|Industrial Foregoing|Buuz135|
|Industrial Wires|malte0811|
|Integrated Dynamics|kroeser|
|Integrated Tunnels|kroeser|
|Interaction Wheel|McJty|
|Level Up! 2|BeetoGuy|
|Lost Cities, The|McJty|
|Mechanical Soldiers|The_Fireplace|
|NICE|McJty|
|NotEnoughWands|McJty|
|OpenComputers|OpenComputers Team|
|OpenGlasses|marcin212|
|Overlord|The_Fireplace|
|Random Things|Lumien|
|RFTools|McJty|
|RFTools Control|McJty|
|RFTools Dimensions|McJty|
|Rustic|mangoose|
|Scannable|Sangar|
|Similsax Transtructors|Lothrazar|
|Simple Storage Network|Lothrazar|
|Spectrite|FlashfireEX|
|Steve's Carts|Team Reborn|
|???|amadornes|
|TechReborn|Team Reborn|
|Teckle|darkevilmac|
|Thermionics|Falkreon|
|TIS-3D|Sangar|
|Totemic|ljfa|
|Unique Crops|bafomdad|
|Wearable Backpacks|copygirl|
|XNet|McJty|
|Zetta Industries|marcin212

**Comment by TartaricAcid** [comment]
@Aemande123 Hope you can help me translation.

**Comment by Towdium** [comment]
Will take a look when I have time.

By the way, if anyone find mods to be supported by JustEnoughCharacters, please let me know.  
You can always find me here:
https://github.com/Towdium/JustEnoughCharacters/issues/3

**Comment by asiekierka** [comment]
Thanks for information on JustEnoughCharacters, by the way! Do you think it would be a good idea to add it as an optional mod? (Selectable in the launcher through a checkbox)

**Comment by Towdium** [comment]
@asiekierka Great! It's my honour. The old versions could have some compatibility issue since I was new to coremod programming, but I have been quite careful with the new version and only focuse on certain pices of code. For the new version, no compatibility issue has been reported so far.

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/issues/150
I open a new issues to track translation progress.
