### ISSUE TITLE
整合包 Modern Skyblock 2 汉化请求

### ISSUE THREAD

**Issue by Aspen581** [TartaricAcid/Minecraft-Mod-Language-Package#124]
版本是1.12.1，一个空岛类型的整合包
因为是新思路的资源获取方式，其指南没有汉化造成了很大的困难
希望能加入您的汉化计划中

**Comment by TartaricAcid** [comment]
收到

**Comment by 3TUSK** [comment]
@Aspen581 整合内手册等汉化请移步 https://github.com/TartaricAcid/Modpack-GuideBook-i18n

**Comment by Aspen581** [comment]
非常感谢

**Comment by TartaricAcid** [comment]
https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/issues/149
目前还没有完成，不过之后会补全列表。

**Comment by zxc3641289** [comment]
https://github.com/TartaricAcid/Modpack-GuideBook-i18n没有Modern Skyblock 2的汉化手册，或者我看不懂。而且Modern Skyblock 2的版本是1.12.2.放在1.10.2的项目里不好吧。

**Comment by TartaricAcid** [comment]
Modern Skyblock 2 汉化项目目前还未开启，恐怕还得延期 @zxc3641289
