### ISSUE TITLE
BTM Moon 汉化进度表

### ISSUE THREAD

**Issue by TartaricAcid** [TartaricAcid/Minecraft-Mod-Language-Package#150]
Here it is the mirrored mod list from BTM Moon, used for tracking translation progress.    
This list will be update regularly (before the list is settle down), please check regularly.

下表为 http://btm.mcft.net/moon/ 上的 mod 列表的镜像，用于跟踪翻译进度。在最终 mod 列表确定前都会定期更新，请定期查阅。

- [ ] AbyssalCraft Integration
- [ ] AbyssalCraft
- [x] aquamunda
- [x] Architect
- [x] Aroma1997s Dimensional
- [ ] autoverse
- [ ] binnie mods
- [x] CD4017BE
- [x] Charset
- [x] ChickenChunks
- [ ] ClassyHats
- [x] ClaySoldiersMod
- [x] Computronics
- [ ] Correlated
- [ ] crossroads
- [ ] dissolution
- [x] elementaldimensions
- [x] enderutilities
- [x] EnergeticSheep
- [ ] Engination
- [ ] ExtraBitManipulation
- [x] ForecastersBackpacks
- [ ] forestry
- [x] FruitPhone
- [ ] Genera
- [x] GlassHearts
- [ ] Hwyla
- [ ] ImmersiveEngineering
- [ ] ImmersiveRailroading
- [ ] InductiveLogistics
- [ ] IntegratedDynamics
- [x] IntegratedTunnels
- [x] intwheel
- [ ] LittleTiles
- [ ] MagicBooks
- [ ] Magneticraft
- [x] MechSoldiers
- [x] OnlinePicFrame
- [ ] rftools
- [x] SBM BoneTorch
- [x] towel
- [x] Tri Addon
- [ ] TurretMod
- [x] uniquecrops
- [ ] UpAndDownAndAllAround
- [x] VE FluidHandling
- [ ] Wings
- [x] WirelessCraftingTerminal
- [ ] wizardry

**Comment by asiekierka** [comment]
Please remember that the list of mods has not been finalized. I will try to keep you updated in this issue, however. The list of mods should be closed by the end of October.

**Comment by TartaricAcid** [comment]
@asiekierka Thanks

**Comment by asiekierka** [comment]
mxTune has been removed from the list. A large mod list update should come soon.

**Comment by 3TUSK** [comment]
> InventoryNeko

Wow.

**Comment by 3TUSK** [comment]
@TartaricAcid Mod list is most likely frozen. https://twitter.com/modmuss50/status/919539482390614021

**Comment by drcrazy** [comment]
towel mod available here: 
https://github.com/drcrazy/Towel

**Comment by Mrkwtkr** [comment]
Got it :P

**Comment by 3TUSK** [comment]
I think we can close this now...

**Comment by Mrkwtkr** [comment]
Call @TartaricAcid
