### ISSUE TITLE
请求汉化EnderRift MOD 版本为1.11.2

### ISSUE THREAD

**Issue by hb3511** [TartaricAcid/Minecraft-Mod-Language-Package#162]
我，[hb3511]，同意对于本项目的贡献的许可协议，[知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议](https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/blob/master/LICENSE)。（如果你是之前的贡献者或你不需要它，可以移除）
请求汉化EnderRift MOD 版本为1.11.2 麻烦了。
- [是] 请求汉化

[en_US.zip](https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/files/1400722/en_US.zip)

**Comment by TartaricAcid** [comment]
抱歉，目前暂时没有任何汉化1.11.2相关模组的计划。
