### ISSUE TITLE
EIO、MEK缺失部分汉化

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [TartaricAcid/Minecraft-Mod-Language-Package#26]
很明显，从lang行数就看得出来

**Comment by TartaricAcid** [comment]
我等会儿就会检索这两个模组，多谢提醒

**Comment by mgdgfbhevdyeh** [comment]
对了环境科技新版本多了些成就条目

achievement.environmentaltech.open_guide=获得知识
achievement.environmentaltech.open_guide.desc=打开数字教程手册
achievement.environmentaltech.craft_assembler=开始装配
achievement.environmentaltech.craft_assembler.desc=制作一个装配杆
achievement.environmentaltech.craft_colored_lens=聚集激光
achievement.environmentaltech.craft_colored_lens.desc=染色透镜
achievement.environmentaltech.craft_modifier_core=修改
achievement.environmentaltech.craft_modifier_core.desc=制作一个强化核心
achievement.environmentaltech.craft_modifier_speed=加速
achievement.environmentaltech.craft_modifier_speed.desc=制作速度强化核心
achievement.environmentaltech.craft_modifier_piezo=振动的能量
achievement.environmentaltech.craft_modifier_piezo.desc=制作压电强化部件
achievement.environmentaltech.craft_modifier_accuracy=增强聚集激光
achievement.environmentaltech.craft_modifier_accuracy.desc=制作一个精度强化部件
achievement.environmentaltech.craft_modifier_jump_boost=我腿上的弹簧
achievement.environmentaltech.craft_modifier_jump_boost.desc=制作跳跃增强强化部件
achievement.environmentaltech.craft_modifier_flight=纳米技术让你飞行
achievement.environmentaltech.craft_modifier_flight.desc=制作飞行修改器
achievement.environmentaltech.craft_modifier_resistance=减少伤害
achievement.environmentaltech.craft_modifier_resistance.desc=制作电阻强化部件
achievement.environmentaltech.craft_modifier_fire_res=减速火焰伤害
achievement.environmentaltech.craft_modifier_fire_res.desc=减少防火强化部件
achievement.environmentaltech.craft_modifier_haste=更快
achievement.environmentaltech.craft_modifier_haste.desc=制作极速强化插件
achievement.environmentaltech.craft_modifier_strength=增加你受到的伤害
achievement.environmentaltech.craft_modifier_strength.desc=制作强度强化部件
achievement.environmentaltech.craft_modifier_night_vision=在黑暗中看到
achievement.environmentaltech.craft_modifier_night_vision.desc=制作夜视强化部件
achievement.environmentaltech.craft_modifier_water_breathing=水下呼吸
achievement.environmentaltech.craft_modifier_water_breathing.desc=制作一个水下呼吸强化部件
achievement.environmentaltech.craft_modifier_regen=快速治疗
achievement.environmentaltech.craft_modifier_regen.desc=制作再生强化插件
achievement.environmentaltech.craft_modifier_saturation=自动输送
achievement.environmentaltech.craft_modifier_saturation.desc=制作饱和强化部件

**Comment by TartaricAcid** [comment]
多谢提醒，回头会补充好的

**Comment by TartaricAcid** [comment]
已经被修复：https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/commit/40987f9320806aa7de14d2ce3f99a8a0c875ad86
以及，MEK的汉化我特意看了下，中英文都是1110行，没发现问题，你确认你用的是`Mekanism-1.10.2-9.2.2.301`版本？

**Comment by mgdgfbhevdyeh** [comment]
好吧确定是我版本低
