### ISSUE TITLE
Could you divide all mods into separate packs?

### ISSUE THREAD

**Issue by 1793907272** [TartaricAcid/Minecraft-Mod-Language-Package#53]

**Comment by 3TUSK** [comment]
Reason?

**Comment by TartaricAcid** [comment]
为啥要分开？我的反驳观点如下：
1. 资源包加载形式方便之处就在于即使一些模组你没有装，这些多出来的本地化也不会对游戏造成**任何**影响。
2. 即使现在包含了200多个模组，可是做成的资源包大小只有不到800K，从大小上来说可能还不及一张图片来的大。
3. 集合在一起方便管理，分成多个包无形中增加了工作量。

**Comment by RelaperCrystal** [comment]
YOU CAN ADD **200+** RESOURCE PACKS ON **ONE GAME**!!!!!!!!!!????????? Ceylan can't do this.
