### ISSUE TITLE
Craft of the titans

### ISSUE THREAD

**Issue by Aknightofvoid** [TartaricAcid/Minecraft-Mod-Language-Package#55]
可以汉化这个整合包吗

**Comment by mgdgfbhevdyeh** [comment]
你好
所依赖Mod大多已经汉化
如果有没汉化的，提供Mod名字。

**Comment by Aknightofvoid** [comment]
有个任务书mod里面的任务可以汉化吗

**Comment by Aknightofvoid** [comment]
是betterquesting的任务mod

**Comment by mgdgfbhevdyeh** [comment]
任务书不是Mod的内容
是个json
3T一句话你应该看看
![default](https://cloud.githubusercontent.com/assets/20567492/26532866/9794cb82-443f-11e7-9d00-08bc09b5d70a.PNG)

**Comment by mgdgfbhevdyeh** [comment]
那本书不可能汉化
因为那不是Mod本身的内容
只是个json

**Comment by Aknightofvoid** [comment]
还有一些mod
比如：
ViesCraft , Think Big Core, Ad Inferos, iChunUtil, ITank, Translocators, TitanTrinkets, tinker_io, tesla-core-lib, SpartanShields, Slugs Converters, SimplyJetpacks2(汉化未全), simpleores, SimpleTcon, StandardExpansion, SeriousCreeper's Crafting Runes, ScalingHealth, prefab, plustic, openmodularturrets, NuclearCraft, mysticalagriculture(汉化不全), MikeDongles, mekfarm, teleporters, kitchensink, inventorypets, GrimoireOfGaia3, FarmingForBlockheads, Enchiridion, DragonRealm, deadly_monsters, Creative Plus, BetterQuesting, baublesstuff, avaritiaadditions, agricraft(汉化未全), sccraftingrunes

**Comment by Aknightofvoid** [comment]
这些都是mods文件夹里的mod名称，可能会和游戏内JEI里的mod名字不同

**Comment by Aknightofvoid** [comment]
如果能汉化的话就太感谢了！！

**Comment by Aknightofvoid** [comment]
那为啥invasion里的任务书里的内容可以汉化？

**Comment by TartaricAcid** [comment]
mods汉化我等会检索一下，手册的汉化看昨天我开的一个仓库

**Comment by TartaricAcid** [comment]
已经设立好了
https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/issues/57
