### ISSUE TITLE
futurepack mod缺失大量汉化

### ISSUE THREAD

**Issue by yuanjie000** [TartaricAcid/Minecraft-Mod-Language-Package#60]
原汉化者已经1年没动静了
[mod作者的汉化提交处](https://github.com/mcenderdragon/FuturePack-Language)
量有点大

**Comment by TartaricAcid** [comment]
已经添加到项目中https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/commit/b1ddbeb89868d0cc5c7494d8adaa258d6abf6d14
