### ISSUE TITLE
1.10.2 Extra Utilities 手册汉化乱码

### ISSUE THREAD

**Issue by ZeroAurora** [TartaricAcid/Minecraft-Mod-Language-Package#74]
![2017-07-05_15 03 10](https://user-images.githubusercontent.com/25359455/27854135-1cf91ee8-6198-11e7-984b-fbb59a597986.png)
![2017-07-05_15 03 25](https://user-images.githubusercontent.com/25359455/27854166-3da19652-6198-11e7-9c65-051ec93c15c1.png)

**Comment by 3TUSK** [comment]
Nonsense.  
为什么不是**所有的**内容都是乱码？请求检查整本书。

**Comment by ZeroAurora** [comment]
确实是整本书都乱码了。。客户端还在开，图片稍后上传

**Comment by TartaricAcid** [comment]
乱码的问题是作者没有强制使用UTF-8编码导致的，你可以在游戏启动参数里面设定强制使用UTF-8编码。或者手动将手册改为GB2312编码（好像ANSI编码也可以）

**Comment by ZeroAurora** [comment]
理解，Thanks.

**Comment by ZeroAurora** [comment]
请教如何修改启动参数？还是直接在语言菜单选中强制使用Unicode代码？

**Comment by 3TUSK** [comment]
语言选单中那个强制 Unicode 只是改字体用的。
如果要强制使用utf8，你需要一些特殊的方法...

**Comment by TartaricAcid** [comment]
@ZeroAurora 给你的启动器增加一个`-Dfile.encoding=UTF-8`参数就行

**Comment by ZeroAurora** [comment]
了解，改手册编码为GB2312已经修复
谢谢~

**Comment by 3TUSK** [comment]
（等于没修复...OS X/*nix用户不可能用这种花里胡哨的编码的。）

**Comment by TartaricAcid** [comment]
@3TUSK 所以用增加启动参数的方式绝对是万金油
