### ISSUE TITLE
Space Astronomy 2 汉化

### ISSUE THREAD

**Issue by Aknightofvoid** [TartaricAcid/Minecraft-Mod-Language-Package#85]
求大佬汉化，谢谢了

**Comment by TartaricAcid** [comment]
请提供缺失本地化的模组列表

**Comment by Aknightofvoid** [comment]
以前不是你检索的么......

**Comment by TartaricAcid** [comment]
我可以偷个懒么？

**Comment by Aknightofvoid** [comment]
好吧，我有空去看看

**Comment by Aknightofvoid** [comment]
@TartaricAcid 需要提供mod的文件名称还是在游戏内mod的名称

**Comment by 3TUSK** [comment]
游戏内Mod名称可能更好。

**Comment by Aknightofvoid** [comment]
@TartaricAcid  [Space Astronomy 2 汉化.txt](https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/files/1189340/Space.Astronomy.2.txt)

**Comment by TartaricAcid** [comment]
@Aknightofvoid https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/issues/105
