### ISSUE TITLE
【汉化申请】可否增加更多生物MOD的汉化？

### ISSUE THREAD

**Issue by hb3511** [TartaricAcid/Minecraft-Mod-Language-Package#86]
你好，麻烦问下可否增加更多生物MOD（DrZharks MoCreatures）版本 1.10.2的汉化文件？谢谢。
由于我是第一次使用这个论坛（？）所以如果使用错误造成了打扰还请见谅，谢谢。

附件是1.10.2的文件，我汉化了部分商品。
[en_US.zip](https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/files/1175767/en_US.zip)

**Comment by TartaricAcid** [comment]
等会儿我手动添加上去
github是一个基于git的代码托管网站，不能算论坛吧。

**Comment by hb3511** [comment]
好的，谢谢。
那个说真的。我是新人 也是第一次用这个网站，所以很多东西不懂，还请见谅哈。

**Comment by TartaricAcid** [comment]
没事，好好看好好学~(～￣▽￣)～

**Comment by hb3511** [comment]
谢谢哈  ^_^

**Comment by TartaricAcid** [comment]
已经加上，翻译目前还未进行，请稍等一段时间（考虑到严谨性，现在暂时还没有参考你的翻译文件，还望见谅）
具体查看：https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/commit/bcd9c72cad74cd662de7fff1871f294ca446536f

**Comment by hb3511** [comment]
十分感谢。
理解，毕竟我只是个外行人，如果参考我的文件，结果造成了大家更多的工作量，那我也会很不好意思。
谢谢。

**Comment by TartaricAcid** [comment]
没有没有，只是这个模组属于比较经典的模组，我刚刚让别人去找原来1.7.10时候HAYO翻译的文件去了

**Comment by hb3511** [comment]
再次说声感谢。
那就不打扰你了，谢谢。

**Comment by TartaricAcid** [comment]
汉化已经补全：https://github.com/TartaricAcid/Minecraft-Mod-Language-Package/commit/078652466a8514f0b985c98f63c30a3598d634a8

**Comment by hb3511** [comment]
十分感谢。
