### ISSUE TITLE
请求跟进BetterQuesting汉化

### ISSUE THREAD

**Issue by ZeroAurora** [TartaricAcid/Minecraft-Mod-Language-Package#89]
想做1.10.2的整合，使用HQM会导致一系列问题，而BQ又没有汉化。。

BQ的lang文件是在五月(还是六月)添加的，但是直到现在还没有开始翻译。

自己尝试着汉化，发现里面如果使用机翻+手动翻译修正会有一些意义不清，例如 __Edit Quests__ 和 __Edit Tasks__ 都翻译为“编辑任务”

**Comment by TartaricAcid** [comment]
记下了，完成后会通知你

**Comment by TartaricAcid** [comment]
已经被人完成了
